config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :members
  #root 'home#index'
  root 'members#index'

  get 'home/about'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord

	belongs_to :user


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :members
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
    
  
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index,:show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /members or /members.json
  def index
    @members = Member.all
  end

  # GET /members/1 or /members/1.json
  def show
  end

  # GET /members/new
  def new
    #@member = Member.new
    @member = current_user.members.build
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members or /members.json
  def create
    #@member = Member.new(member_params)
    @member = current_user.members.build(member_params)
    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: "Member was successfully created." }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1 or /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: "Member was successfully updated." }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1 or /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: "Member was successfully destroyed." }
      format.json { head :no_content }
    end
  end


  def correct_user
    @member = current_user.members.find_by(id: params[:id])
    redirect_to members_path, notice: "Not Authorized to Edit this Friend" if @member.nil?
  end







  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def member_params
      params.require(:member).permit(:first_name, :last_name, :email, :phone, :twitter, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">

  	<%= link_to 'GDN', root_path, class:'navbar-brand' %>

    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      
        <li class="nav-item">

        	<%= link_to 'About us', home_about_path, class:"nav-link active" %>
        </li>


          


        <% if user_signed_in? %>

            <li class="nav-item">

              <%= link_to 'Add Member', new_member_path, class:"nav-link active" %>
             </li>




            <li class="nav-item">

             <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class:"nav-link active" %>
            </li>

            <li class="nav-item">

            <%= link_to 'Edit Profile', edit_user_registration_path, class:"nav-link active" %>
            </li>
        
        <% else %>
           <li class="nav-item">         

            <%= link_to 'Sign Up', new_user_registration_path, class:"nav-link active" %>
          </li>


           <li class="nav-item">

            <%= link_to 'Sign in', new_user_session_path, class:"nav-link active" %>
            </li>
        <% end %>


        

         


        
       
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>Who are we !</h1>

app/views/home/index.html.erb
<h1>Welcome to Gurudatta Nagar</h1>
<h2>We are happy to see you here !</h2>

<% s = 'Are you Okay?' %>
<%= s %>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>GDN-complex</title>

      <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>




  </head>
  <body>

    <%= render 'home/header' %>

    <div class="container">
      <br>
      <p class="notice"> <%= notice %> </p>
      <br>
      <%= yield %>


    </div>

    

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/members/_form.html.erb
<%= form_with(model: member) do |form| %>
  <% if member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
        <% member.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :twitter %>
    <%= form.text_field :twitter %>
  </div>

   <div class="field">
    <%= form.number_field :user_id, id: :member_user_id, value: current_user.id, type: :hidden %>
  </div>




  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/members/edit.html.erb
<h1>Editing Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>
<%= link_to 'Delete', @member, method: :delete, data: { confirm: 'Are you sure?' } , class:"btn btn-danger" %>

app/views/members/index.html.erb
<% if user_signed_in? %>

<p id="notice"><%= notice %></p>

<h1>Members List</h1>

<table class="table table-striped table-bordered table-hover">
  <thead >
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Twitter</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @members.each do |member| %>
    <% if member.user == current_user %>
      <tr>
        <td><%= link_to member.first_name + ' ' + member.last_name, member %></td>
        <td><%= member.email %></td>
        <td><%= member.phone %></td>
        <td><%= member.twitter %></td>
        <td><%= link_to 'Delete', member, method: :delete, data: { confirm: 'Are you sure?' } , class:"btn btn-outline-danger btn-sm" %></td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Member', new_member_path, class:"btn btn-secondary" %>

<% else %>
<h1>Welcome to Gurudatta Nagar</h1>
<h2>We are happy to see you here !</h2>

<% s = 'Are you Okay?' %>
<%= s %>


<% end %>

app/views/members/new.html.erb
<h1>Add New Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Back', members_path %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @member.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @member.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @member.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @member.phone %>
</p>

<p>
  <strong>Twitter:</strong>
  <%= @member.twitter %>
</p>

<%= link_to 'Edit', edit_member_path(@member), class:"btn btn-secondary" %> |
<%= link_to 'Back', members_path, class:"btn btn-dark" %>